# Generated by Django 2.2.5 on 2019-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_day', models.DateField(verbose_name='発表日')),
                ('category', models.CharField(choices=[('I', 'INFO'), ('S', 'SERVICE'), ('W', 'WORK'), ('T', 'TECH')], max_length=1, verbose_name='カテゴリ')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('content', models.TextField(max_length=4096, verbose_name='本文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wphotos', verbose_name='イメージ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='関連リンク')),
                ('votes', models.IntegerField(default=0, verbose_name='いいね数')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='登録日')),
            ],
        ),
    ]
