# Generated by Django 2.2.5 on 2019-11-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Topic',
        ),
    ]
