# Generated by Django 2.2.5 on 2019-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebase', '0002_auto_20191110_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tphotos', verbose_name='イメージ'),
        ),
    ]
